package net.darkhax.gyth;

import java.util.Arrays;

import net.darkhax.gyth.common.ProxyCommon;
import net.darkhax.gyth.utils.Constants;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInterModComms;
import cpw.mods.fml.common.event.FMLInterModComms.IMCMessage;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Constants.MODID, name = Constants.MOD_NAME, version = Constants.VERSION, dependencies = "required-after:Waila")
public class Gyth {

    @SidedProxy(serverSide = Constants.SERVER, clientSide = Constants.CLIENT)
    public static ProxyCommon proxy;

    @Mod.Instance(Constants.MODID)
    public static Gyth instance;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {

        setModMeta(event.getModMetadata());
    }

    @EventHandler
    public void messageRecieved(FMLInterModComms.IMCEvent event) {

    }

    void setModMeta(ModMetadata meta) {

        meta.authorList = Arrays.asList("Darkhax");
        meta.credits = "Coded by Darkhax";
        meta.description = "This mod adds a modular tank system.";
        meta.autogenerated = false;
    }
}